José Luis Roberto Zárate Cortés (000183347)
# Semana 3; Clase 3_algebra_lineal, 1_ecuaciones_lineales
Ejercicio: resolver los sistemas de ecuaciones lineales $$Ax=B$$ con la factorización P, LU y verificar resultado

In [2]:
import scipy
import scipy.linalg 
import numpy as np
import pprint

In [4]:
MatA = scipy.array([[ 0, 1, -1], [ -2, 4, -1], [ -2, 5, -4]])
MatB = scipy.array([[ 3, -5], [ 1, 7], [ -2, 0]])

P, L, U = scipy.linalg.lu(MatA)

print('Matriz A:')
pprint.pprint(MatA)
print('Matriz P:')
pprint.pprint(P)
print('Matriz L:')
pprint.pprint(L)
print('Matriz U:')
pprint.pprint(U)

Matriz A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
Matriz P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
Matriz L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
Matriz U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])


In [10]:
D = scipy.linalg.solve_triangular(L,P@MatB,lower=True)
VSol = scipy.linalg.solve_triangular(U,D)
print('Vector Solución:')
pprint.pprint(VSol)

Vector Solución:
array([[ 10., -12.],
       [  6.,  -4.],
       [  3.,   1.]])


In [11]:
print('Validar vector solución Ax = B')
print('MatB:')
pprint.pprint(MatB)
print('Ax:')
pprint.pprint(MatA@VSol)

Validar vector solución Ax = B
MatB:
array([[ 3, -5],
       [ 1,  7],
       [-2,  0]])
Ax:
array([[ 3., -5.],
       [ 1.,  7.],
       [-2.,  0.]])
