José Luis Roberto Zárate Cortés (000183347)
# Semana 3; Clase 3_algebra_lineal, 1_ecuaciones_lineales
Ejercicio: resolver el ejercicio 3) con la factorización QR del paquete numpy de la matriz A y verificar resultado.
$$Ax=B$$

In [1]:
import scipy
import scipy.linalg 
import numpy as np
import pprint

In [2]:
MatA = scipy.array([[2, -1, 2], [1, 6, -1], [1, 4, 1]])
MatB = scipy.array([[7, -1], [13, 6], [5, 7]])

In [3]:
pprint.pprint(MatA)
pprint.pprint(MatB)

array([[ 2, -1,  2],
       [ 1,  6, -1],
       [ 1,  4,  1]])
array([[ 7, -1],
       [13,  6],
       [ 5,  7]])


In [4]:
Q,R = scipy.linalg.qr(MatA)
QT=np.transpose(Q)

In [5]:
print("Matriz Q:")
pprint.pprint(Q)
print("Matriz R:")
pprint.pprint(R)
print("Matriz QT:")
pprint.pprint(QT)

Matriz Q:
array([[-0.81649658,  0.56354707, -0.12549116],
       [-0.40824829, -0.71724173, -0.56471022],
       [-0.40824829, -0.40985242,  0.81569255]])
Matriz R:
array([[-2.44948974, -3.26598632, -1.63299316],
       [ 0.        , -6.5064071 ,  1.43448345],
       [ 0.        ,  0.        ,  1.12942045]])
Matriz QT:
array([[-0.81649658, -0.40824829, -0.40824829],
       [ 0.56354707, -0.71724173, -0.40985242],
       [-0.12549116, -0.56471022,  0.81569255]])


In [6]:
pprint.pprint(Q@R) # Validación de QR=A
pprint.pprint(Q@QT)# Validación de Q'Q=I

array([[ 2., -1.,  2.],
       [ 1.,  6., -1.],
       [ 1.,  4.,  1.]])
array([[ 1.00000000e+00,  1.52655666e-16, -1.38777878e-17],
       [ 1.52655666e-16,  1.00000000e+00, -5.55111512e-17],
       [-1.38777878e-17, -5.55111512e-17,  1.00000000e+00]])


In [7]:
#Resolviendo Rx=QTB
VSol = scipy.linalg.solve_triangular(R,QT@MatB)
print("Vector Sol:")
pprint.pprint(VSol)

Vector Sol:
array([[ 7.33333333, -1.83333333],
       [ 0.33333333,  1.66666667],
       [-3.66666667,  2.16666667]])


In [8]:
print('Validar solución AX = B')
print('Matriz B:')
pprint.pprint(MatB)
print('VectAX:')
pprint.pprint(MatA@VSol)

Validar solución AX = B
Matriz B:
array([[ 7, -1],
       [13,  6],
       [ 5,  7]])
VectAX:
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])
