José Luis Roberto Zárate Cortés (000183347)
# Semana 3; Clase 3_algebra_lineal, 1_ecuaciones_lineales
Ejercicio: resolver los sistemas de ecuaciones lineales $$Ax=B$$ con la factorización P, LU y verificar resultado

In [1]:
import scipy
import scipy.linalg 
import numpy as np
import pprint

In [2]:
MatA = scipy.array([[ 1, 2, 2], [ 2, 5, 7], [ 3, 6, 6]])
MatB = scipy.array([0,0,0])
pprint.pprint(MatB)
P, L, U = scipy.linalg.lu(MatA)

print('Matriz A:')
pprint.pprint(MatA)
print('Matriz P:')
pprint.pprint(P)
print('Matriz L:')
pprint.pprint(L)
print('Matriz U:')
pprint.pprint(U)

array([0, 0, 0])
Matriz A:
array([[1, 2, 2],
       [2, 5, 7],
       [3, 6, 6]])
Matriz P:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
Matriz L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.        , 1.        ]])
Matriz U:
array([[3., 6., 6.],
       [0., 1., 3.],
       [0., 0., 0.]])


In [3]:
D = scipy.linalg.solve_triangular(L,P@MatB,lower=True)
pprint.pprint(D)
#VSol = scipy.linalg.solve_triangular(U,D)
#print('Vector Solución:')
#pprint.pprint(VSol)

array([0., 0., 0.])


AL observar la matriz A, observamos que existe redundancia entre renglones, que se puede corroborar en la Matriz, por lo tanto asignamos la tercer variable libre y a partir de esta construimos nuestro Vector Solución:

Sea z libre, entonces y+3z=0 -> y=-3z y 3x+6(-3z)+6z=0 -> x=4z
$$VSol=array([4z, -3z, z])$$

In [4]:
VSol=([28,-21,7])
print('Validar vector solución Ax = B')
print('MatB:')
pprint.pprint(MatB)
print('Ax:')
pprint.pprint(MatA@VSol)

Validar vector solución Ax = B
MatB:
array([0, 0, 0])
Ax:
array([0, 0, 0])
